language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
# deploy:
#   provider: surge
#   skip_cleanup: true
#   domain: <my_name_here>.surge.sh
#   project: ./build/
on:
  branch: master

# before_install:
#   - chmod +x scripts/*
# install: npm install
# jobs:
#   include:
#     # - stage: Tests
#     #   name: "Static Analyis"
#     #   script: python scripts/lint.py
#     - name: "Unit Tests"
#       script: ./scripts/test.sh
